[package]
name = "webmetro"
version = "0.2.0"
authors = ["Tangent 128 <Tangent128@gmail.com>"]

[dependencies]
bytes = "0.4.10"
clap = "2.32.0"
futures = "0.1.25"
http = "0.1"
hyper = "0.12"
odds = { version = "0.3.1", features = ["std-vec"] }
tokio = "0.1.11"
tokio-codec = "0.1.1"
tokio-io = "0.1.10"
warp = "0.1"
weak-table = "0.2"
