[package]
name = "webmetro"
version = "0.2.3-dev"
authors = ["Tangent 128 <Tangent128@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "^0.4.12"
clap = "^2.33.0"
custom_error = "^1.7"
env_logger = "^0.7"
futures = "0.1.29"
futures3 = { package = "futures-preview", version="0.3.0-alpha", features = ["compat"] }
http = "^0.1.18"
hyper = "^0.12.35"
hyper13 = { package = "hyper", version="0.13.0-alpha.4", features = ["unstable-stream"] }
log = "^0.4.8"
matches = "^0.1.8"
odds = { version = "0.3.1", features = ["std-vec"] }
tokio = "0.1.22"
tokio2 = { package = "tokio", version="0.2.0-alpha.6" }
tokio-codec = "0.1.1"
tokio-io = "0.1.12"
warp = "0.1.20"
weak-table = "^0.2.3"
